package:
  name: cgpm
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  # taken from https://github.com/probcomp/cgpm/blob/ebaf5eedf9f5ad721eeecf6a0d30b60d59b3832d/setup.py#L168...L175
  # version numbers were modified to get tests to pass
  build:
    - git
    - matplotlib 1.5.1
    - numpy 1.11.0
    - python 2.7.*
  run:
    - matplotlib 1.5.1
    - numpy 1.11.0
    - pandas 0.17.1
    - python 2.7.*
    - scipy 0.17.0
    - scikit-learn 0.17.*
    - statsmodels 0.6.1

test:
  requires:
    - matplotlib 1.5.1
    - pytest 2.8.7
    - python 2.7.*
  imports:
    - cgpm
  commands:
    - python -m pytest --pyargs cgpm -k "not __ci_"

about:
  home: https://github.com/probcomp/cgpm
  license: Apache
  license_file: LICENSE.txt
